name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Key
        run: |
          echo "Private key:"
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "Public key:"
          ssh-keygen -y -f <(echo "${{ secrets.SSH_PRIVATE_KEY }}")

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") user@remote-server-ip "
            cd /var/www/my-app &&
            git fetch origin main &&
            git reset --hard origin/main
          "
